# This starts two services, app and database

services:
    app:
      container_name: app
      build: ./app
   #       context: .
   #       target: app
   #   volumes:
   #     - './app:/app'
   #     - '/app/node_modules'
      ports:
        - 7555:3000
      environment:
        - CHOKIDAR_USEPOLLING=true
    # web:
    #     container_name: web
    #     build:
    #       context: .
    #       target: web
    #     ports:
    #       - "7555:5000"
    # api:
    #     container_name: api
    #     build:
    #       context: .
    #       target: api
    #     expose:
    #       - "5000"
    db:
      container_name: db
      image: mysql
      expose:
        - "3306"
      environment:
        MYSQL_ROOT_PASSWORD: thebestgame
        restart: on-failure
      volumes:
        - ./database:/docker-entrypoint-initdb.d/
        # - ./db-storage:/var/lib/mysql
